### ISSUE TITLE
Discuss Kafka protocol

### ISSUE THREAD

**Issue by DenisNovac** [Baklanov-Soft/image-hosting-processing#1]

**Comment by adedw** [comment]
Should I put image ID as the object name in minio?
Thus filename maybe non unique in metadata?
Suggest the next message structure:
`userId (bucket): guid`
`imageId: guid`

**Comment by DenisNovac** [comment]
From discussion with @adedw : 

- message schema:
```
{
    "bucketId": "2b260a92-c9c3-42df-afdd-6c49591369d0",
    "imageId": "31622860-3e1e-4d47-9dac-3b30d006ba6f"
}
```
- topic `new-images.v1` with 2 partitions and 1 replica (initialized by storage but manual for now);
- previews will be written into `bucketId/previews/<RES>/image-id` where `<RES>` enum will be provided as the outcome of technical task.
